# Development config with verbose logging
general:
  port: 3000
  verbose: true
  https:
    enabled: false
  session_id:
    header_name: "X-Session-ID"
    required: false
  inference_provider: "ollama"
  language_detection: true
  inference_only: false
  adapter: "qa-vector-chroma"

messages:
  no_results_response: "I'm sorry, but I don't have any specific information about that topic in my knowledge base."
  collection_not_found: "I couldn't find the requested collection. Please make sure the collection exists before querying it."

embedding:
  provider: "ollama"
  enabled: true

api_keys:
  header_name: "X-API-Key"
  prefix: "orbit_"

logging:
  level: "DEBUG"
  handlers:
    file:
      enabled: true
      directory: "logs"
      filename: "orbit-dev.log"
      max_size_mb: 10
      backup_count: 5
      rotation: "midnight"
      format: "text"
    console:
      enabled: true
      format: "text"
  capture_warnings: true
  propagate: true
  loggers:
    inference.clients.llama_cpp:
      level: "DEBUG"
    llama_cpp:
      level: "DEBUG"

internal_services:
  mongodb:
    host: "localhost"
    port: 27017
    database: "orbit_dev"
    apikey_collection: "api_keys"

  redis:
    enabled: true
    host: "localhost"
    port: 6379
    db: 1
    use_ssl: false
    ttl: 3600

chat_history:
  enabled: false

file_upload:
  enabled: true
  max_size_mb: 5
  max_files_per_batch: 5
  allowed_extensions:
    - ".txt"
    - ".pdf"
    - ".docx"
    - ".csv"
    - ".md"
  upload_directory: "uploads_dev"
  save_to_disk: true
  auto_store_in_vector_db: true
  chunk_size: 500
  chunk_overlap: 100

embeddings:
  ollama:
    base_url: "http://localhost:11434"
    model: "nomic-embed-text"
    dimensions: 768

adapters:
  - name: "qa-vector-chroma"
    type: "retriever"
    datasource: "chroma"
    adapter: "qa"
    implementation: "retrievers.implementations.qa.QAChromaRetriever"
    config:
      confidence_threshold: 0.2
      distance_scaling_factor: 200.0
      max_results: 10
      return_results: 5

  - name: "file-vector"
    type: "retriever"
    datasource: "chroma"
    adapter: "file"
    implementation: "retrievers.implementations.file.FileChromaRetriever"
    config:
      confidence_threshold: 0.1
      distance_scaling_factor: 150.0
      max_results: 10
      return_results: 5
      include_file_metadata: true
      boost_file_uploads: true
      file_content_weight: 1.5
      metadata_weight: 0.8

datasources:
  chroma:
    use_local: true
    db_path: "examples/chroma/chroma_db_dev"

inference:
  ollama:
    base_url: "http://localhost:11434"
    temperature: 0.3
    top_p: 0.9
    top_k: 40
    repeat_penalty: 1.1
    num_predict: 2048
    num_ctx: 8192
    num_threads: 8
    model: "gemma3:1b"
    stream: true

safety:
  enabled: false

llm_guard:
  enabled: false

reranker:
  enabled: false 