# config.yaml
# API Key Manager Database Configuration

# General application settings
application:
  name: "API Key Manager"
  log_level: "info"  # debug, info, warning, error, critical
  log_file: "logs/api_manager.log"

# Database connection settings
database:
  # The engine to use (sqlite, postgres, mysql, oracle, mssql)
  engine: "sqlite"
  
  # Connection parameters - these will vary based on the engine
  connection:
    # SQLite specific settings
    sqlite:
      database: "data/api_keys.db"
      
    # PostgreSQL specific settings  
    postgres:
      host: "localhost"
      port: 5432
      database: "api_keys"
      user: "postgres"
      password: "password"
      sslmode: "prefer"  # disable, allow, prefer, require, verify-ca, verify-full
      
    # MySQL specific settings
    mysql:
      host: "localhost"
      port: 3306
      database: "api_keys"
      user: "root"
      password: "password"
      charset: "utf8mb4"
      
    # Oracle specific settings
    oracle:
      host: "localhost"
      port: 1521
      service_name: "XEPDB1"  # or SID: "XE"
      user: "system"
      password: "password"
      
    # Microsoft SQL Server specific settings
    mssql:
      host: "localhost"
      port: 1433
      database: "api_keys"
      user: "sa"
      password: "password"
      driver: "ODBC Driver 17 for SQL Server"  # Depends on installed drivers
      
  # Pool settings (for database engines that support connection pooling)
  pool:
    min_size: 1
    max_size: 10
    timeout: 30  # seconds
    
  # Retry settings for database connections
  retry:
    max_attempts: 3
    backoff_factor: 2  # seconds
    
# API key generation settings
api_keys:
  prefix: "orbit_"
  length: 16  # length of the random part
  characters: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  
# System prompt settings
prompts:
  default_version: "1.0"
  templates_dir: "templates"